spring:
  jpa:
    show-sql: true
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: localhost
    password: localhost
    driver-class-name: com.mysql.cj.jdbc.Driver


